version: "3.9"

services:
  app:
    container_name: "api-simples-dental"
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simples-dental
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - local

  db:
    container_name: db-simples-dental
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "simples-dental"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - vol_db:/var/lib/postgresql/data
    networks:
      - local

volumes:
  vol_db:

networks:
  local: